version: '3'
services:
  webapp:
    build: ./webapp
    image: oitgaden/webapp
    container_name: webapp
    ports:
     - "8080:80"
    depends_on:
      - webapi
  webapi:
    build: ./webapi
    image: oitgaden/webapi
    container_name: webapi
    ports:
     - "8081:80"
  dbserver:
    image: postgres
    container_name: dbserver
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-data:
    driver: local